---
sudo: false
language: ruby
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
rvm:
  - 2.5.0
before_install:
  - gem uninstall bundler
  - gem install bundler -v 1.16.3
script:
  - bundle exec rspec
