---
sudo: false
language: ruby
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
rvm:
  - 2.5.0
bundler_args: --jobs=3 --retry=3
cache: bundler

before_install:
  - gem install bundler -v 1.16
  - gem list | grep bundler
script:
  - bundle exec rspec
