---
sudo: false
language: ruby
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
rvm:
  - 2.5.0
  - 2.6.0
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2.6
  - gemfiles/Gemfile.rails-5.0
  - gemfiles/Gemfile.rails-6.0

matrix:
  allow-failures:
    - rvm: ruby-head
bundler_args: --jobs=3 --retry=3
cache: bundler

before_install:
  # 参考: http://koic.hatenablog.com/entry/ruby-2-2-or-lower-with-gem-install-bundler-on-travis-ci
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
script:
  - bundle exec rspec
