version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - bundle:/bundle
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  bundle:
    driver: local
